server:
  port: 8085

spring:
  data:
    mongodb:
      database: testtest
      uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false

logging:
  level:
    com.mory.*: DEBUG